import turtle
t=turtle.Turtle()
s=turtle.Screen()
s.bgcolor("black")
t.shape("circle")
t.speed('slow')
t.color("white")
t.begin_fill()
t.up()
t.goto(0,-300)
t.down()
t.circle(300)
t.end_fill()
t.color("red")
t.up()
t.goto(-150,-150)
t.down()
t.begin_fill()
t.fd(300)
t.circle(100,90)
t.fd(100)
t.circle(100,90)
t.fd(300)
t.circle(100,90)
t.fd(100)
t.circle(100,90)
t.end_fill()
t.up()
t.goto(0,0)
t.rt(180)
t.fd(50)
t.rt(90)
t.fd(70)
t.down()
t.color("white")
t.begin_fill()
for i in range(3):
	t.rt(120)
	t.fd(140)
t.end_fill()
t.color("black")
t.up()
t.goto(0,-200)
t.write("Youtube LOGO", align='center', font=("Arial",8,'normal','italic','bold','underline'))
t.ht()

turtle.done()